### ISSUE TITLE
Travis CI and Greenkeeper documentation

### ISSUE THREAD

**Issue by blakeembrey** [types/guidelines#2]
Should enable a section on CI. Using Travis CI with a default configuration for multiple TypeScript versions and "stable" node.js. Also, have a step to always enable Greenkeeper and recommending using patch-pinned dependencies. Using this approach, we can actually use Greenkeeper to "notify" us of updates we need to make.

**Comment by felixfbecker** [comment]
You mean adding the source package as patch-pinned devdep? Good idea!

**Comment by unional** [comment]
Does it mean I should change `1.2.1` to `^1.2.1` in the generator?

**Comment by blakeembrey** [comment]
@unional `^` is major pinned, E.g. it's `1.*.*`. I think we'd want either `~` or `1.0.x` usage.

**Comment by unional** [comment]
Thanks. How do I do that from cli? I only know:
- `npm install <pkg> -S` => `^a.b.c`
- `npm install <pkg> --save-exact` => `a.b.c`.

**Comment by blakeembrey** [comment]
I don't think there is a way, sadly. I'll have to check and make sure, but the NPM default is major unless you use exact and I don't think we need the extra noise from exact pinning.

**Comment by felixfbecker** [comment]
what about `npm install pkg@~a.b.c`?

**Comment by unional** [comment]
The generator currently does exact pinning. The rationale is that minor change means there are missing typings.

I do like the idea of leveraging GreenKeeper.

**Comment by blakeembrey** [comment]
@felixfbecker Haha, thanks. Yes, that works 😄 I was thinking about something that does both installing the latest version (without knowing it) and saves it using `~`, but we can definitely just do a `npm info` first and parse it out.

@unional Exact pinning is a bit more of a pain for patch changes though, since those (in theory) should only be code patches and not API changes. The `~` is pinned to minor, so a new minor will be out of date triggering a Greenkeeper message - and anything greater than a patch should be what introduces API changes.

**Comment by unional** [comment]
Yes agree.
`npm info <pkg> dist-tags.latest` then `npm install <pkg>@~<latest> -S`
